BEGIN;

CREATE TABLE "hotels_room" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" text NOT NULL,
    "price_per_night" numeric(10, 2) NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE "hotels_booking" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date_start" date NOT NULL,
    "date_end" date NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "room_id" bigint NOT NULL
);

ALTER TABLE "hotels_booking"
ADD CONSTRAINT "hotels_booking_room_id_a36c4fd7_fk_hotels_room_id"
FOREIGN KEY ("room_id")
REFERENCES "hotels_room" ("id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "hotels_booking_room_id_a36c4fd7"
ON "hotels_booking" ("room_id");

CREATE INDEX "hotels_room_price_per_night_idx"
ON "hotels_room" ("price_per_night");

CREATE INDEX "hotels_room_created_at_idx"
ON "hotels_room" ("created_at");

CREATE INDEX "hotels_booking_room_date_start_idx"
ON "hotels_booking" ("room_id", "date_start");

COMMIT;